site_name: Openshift Bootcamp
pages:
  - Home: README.md
  - About the Course: "openshift-bootcamp.md"
  - Configuring Cluster: "configs.md"
  - Launching Pods: "deploying_pods.md"
  - Creating Deployments: "2. kubernetes_deployment.md"
  - Service Endpoints: "exposing_app_with_service.md"
  - Rollouts and Rollbacks: "rollouts-and-rollbacks.md"
  - Using Configmaps and Secrets: "8. Using Configmaps and Secrets.md"
  - Auto Scaling Capacity with HPA : "6. Kubernetes Autoscaling.md"
  - Mini Project: "6. deploying_sample_app.md"
docs_dir: "chapters"
theme: readthedocs
